"""Generate the terrain layers: shaded relief, rivers and lakes.

    python tools/mapstudio/build_terrain.py

Writes two files, both plain <script> globals so index.html still opens from disk:

    data/relief.js   Natural Earth 1:50m shaded relief, cropped to the course bbox,
                     greyscale JPEG, embedded as a data: URI
    data/water.js    river centrelines and lakes, clipped to the same bbox

The relief is embedded as a data: URI rather than referenced as a file for a
concrete reason: drawing a file:// image onto a canvas taints it, and a tainted
canvas cannot be exported with toBlob(). A data: URI keeps the canvas clean, so
PNG export keeps working.

Downloads are cached in tools/mapstudio/.cache/ so a rebuild costs nothing.

Sources, both public domain (naturalearthdata.com):
  SR_50M                            shaded relief raster
  ne_50m_rivers_lake_centerlines    river centrelines
  ne_50m_lakes                      lakes
"""
import base64
import io
import json
import os
import sys
import urllib.request
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, '.cache')
DATA = os.path.join(HERE, 'data')

# Matches build_land.py. Everything downstream assumes these four numbers.
BBOX = (-22.0, -2.0, 100.0, 60.0)

RELIEF_URL = 'https://naciscdn.org/naturalearth/50m/raster/SR_50M.zip'
RIVERS_URL = ('https://raw.githubusercontent.com/nvkelso/natural-earth-vector/'
              'master/geojson/ne_50m_rivers_lake_centerlines.geojson')
LAKES_URL = ('https://raw.githubusercontent.com/nvkelso/natural-earth-vector/'
             'master/geojson/ne_50m_lakes.geojson')

RELIEF_WIDTH = 3400          # px across the bbox; ~28 px per degree
JPEG_QUALITY = 78
PRECISION = 3


def fetch(url, name):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, name)
    if os.path.exists(path) and os.path.getsize(path) > 1024:
        print('  cached  %s (%.1f MB)' % (name, os.path.getsize(path) / 1e6))
        return path
    print('  fetching %s ...' % name)
    req = urllib.request.Request(url, headers={'User-Agent': 'mapstudio-build/1.0'})
    with urllib.request.urlopen(req, timeout=180) as r, open(path, 'wb') as fh:
        while True:
            chunk = r.read(1 << 20)
            if not chunk:
                break
            fh.write(chunk)
    print('  saved   %s (%.1f MB)' % (name, os.path.getsize(path) / 1e6))
    return path


# ----------------------------------------------------------------- relief

def build_relief():
    from PIL import Image, ImageOps, ImageFilter
    Image.MAX_IMAGE_PIXELS = None

    zpath = fetch(RELIEF_URL, 'SR_50M.zip')
    with zipfile.ZipFile(zpath) as z:
        tif = [n for n in z.namelist() if n.lower().endswith('.tif')]
        if not tif:
            sys.exit('no .tif inside SR_50M.zip')
        with z.open(tif[0]) as fh:
            img = Image.open(io.BytesIO(fh.read())).convert('L')

    w, h = img.size
    ppd = w / 360.0                                   # the raster is global plate carree
    left = int(round((BBOX[0] + 180.0) * ppd))
    right = int(round((BBOX[2] + 180.0) * ppd))
    top = int(round((90.0 - BBOX[3]) * ppd))
    bottom = int(round((90.0 - BBOX[1]) * ppd))
    crop = img.crop((left, top, right, bottom))
    print('  raster %dx%d -> crop %dx%d' % (w, h, crop.size[0], crop.size[1]))

    height = int(round(RELIEF_WIDTH * crop.size[1] / crop.size[0]))
    crop = crop.resize((RELIEF_WIDTH, height), Image.LANCZOS)

    # Natural Earth's relief is deliberately gentle. The map multiplies it over a
    # flat land colour, so push the contrast a little or the mountains disappear.
    crop = ImageOps.autocontrast(crop, cutoff=(1, 1))

    # Canvas composites this with 'overlay', where mid-grey is the no-op value. So
    # recentre the land median on 128: flat ground then leaves the base colour alone
    # and only genuine relief darkens or lightens it.
    hist = crop.histogram()
    total = sum(hist[4:251])
    run, median = 0, 128
    for v in range(4, 251):
        run += hist[v]
        if run >= total / 2:
            median = v
            break
    gain = 1.35
    lut = [max(0, min(255, int(round(128 + (v - median) * gain)))) for v in range(256)]
    crop = crop.point(lut)
    print('  land median %d -> 128, gain %.2f' % (median, gain))

    crop = crop.filter(ImageFilter.UnsharpMask(radius=2, percent=60, threshold=3))

    buf = io.BytesIO()
    crop.save(buf, 'JPEG', quality=JPEG_QUALITY, optimize=True)
    raw = buf.getvalue()
    uri = 'data:image/jpeg;base64,' + base64.b64encode(raw).decode('ascii')

    os.makedirs(DATA, exist_ok=True)
    out = os.path.join(DATA, 'relief.js')
    with open(out, 'w', encoding='ascii') as fh:
        fh.write('// generated by tools/mapstudio/build_terrain.py - do not hand-edit\n')
        fh.write('// Natural Earth 1:50m shaded relief (public domain), cropped to the course bbox.\n')
        fh.write('window.MS_RELIEF = {bbox:%s, src:"%s"};\n' % (json.dumps(list(BBOX)), uri))
    print('  relief  %dx%d, jpeg %.0f KB -> %s (%.1f MB)'
          % (RELIEF_WIDTH, height, len(raw) / 1024.0, out, os.path.getsize(out) / 1e6))


# ----------------------------------------------------------------- water

def inside(p):
    return BBOX[0] <= p[0] <= BBOX[2] and BBOX[1] <= p[1] <= BBOX[3]


def runs_inside(coords):
    """Split a line into the contiguous stretches that fall inside the bbox."""
    out, cur = [], []
    for p in coords:
        if inside(p):
            cur.append(p)
        else:
            if len(cur) > 1:
                out.append(cur)
            cur = []
    if len(cur) > 1:
        out.append(cur)
    return out


def flat(coords):
    seen = []
    for x, y in coords:
        p = (round(x, PRECISION), round(y, PRECISION))
        if not seen or p != seen[-1]:
            seen.append(p)
    return [c for p in seen for c in p]


def lines_of(geom):
    t = geom.get('type')
    if t == 'LineString':
        return [geom['coordinates']]
    if t == 'MultiLineString':
        return list(geom['coordinates'])
    return []


def rings_of(geom):
    t = geom.get('type')
    if t == 'Polygon':
        return list(geom['coordinates'])
    if t == 'MultiPolygon':
        return [r for poly in geom['coordinates'] for r in poly]
    return []


def ring_area(pts):
    a = 0.0
    n = len(pts)
    for i in range(n):
        x0, y0 = pts[i][:2]
        x1, y1 = pts[(i + 1) % n][:2]
        a += x0 * y1 - x1 * y0
    return abs(a) / 2.0


def build_water():
    rivers = []
    gj = json.load(open(fetch(RIVERS_URL, 'ne_50m_rivers.geojson'), encoding='utf-8'))
    for feat in gj.get('features', []):
        rank = feat.get('properties', {}).get('scalerank')
        rank = 8 if rank is None else int(rank)
        for line in lines_of(feat.get('geometry') or {}):
            for run in runs_inside(line):
                f = flat(run)
                if len(f) >= 6:
                    rivers.append({'r': rank, 'p': f})

    lakes = []
    gj = json.load(open(fetch(LAKES_URL, 'ne_50m_lakes.geojson'), encoding='utf-8'))
    for feat in gj.get('features', []):
        for ring in rings_of(feat.get('geometry') or {}):
            pts = [p for p in ring if inside(p)]
            if len(pts) < 6 or ring_area(pts) < 0.02:
                continue
            lakes.append(flat(pts))

    os.makedirs(DATA, exist_ok=True)
    out = os.path.join(DATA, 'water.js')
    with open(out, 'w', encoding='utf-8') as fh:
        fh.write('// generated by tools/mapstudio/build_terrain.py - do not hand-edit\n')
        fh.write('window.MS_WATER = ')
        json.dump({'rivers': rivers, 'lakes': lakes}, fh, separators=(',', ':'))
        fh.write(';\n')
    print('  water   %d river runs, %d lakes -> %s (%.0f KB)'
          % (len(rivers), len(lakes), out, os.path.getsize(out) / 1024.0))


if __name__ == '__main__':
    only = sys.argv[1] if len(sys.argv) > 1 else 'all'
    if only in ('all', 'relief'):
        print('relief:')
        build_relief()
    if only in ('all', 'water'):
        print('water:')
        build_water()
