"""Generate tools/mapstudio/data/land.js from Natural Earth land polygons.

    python tools/mapstudio/build_land.py

Reads series/data/ne_50m_land.geojson, clips it to the course bounding box
(Iberia to Bengal), simplifies, and writes a plain `<script>` global. Emitting a
script rather than JSON is deliberate: Chrome refuses fetch() on file:// URLs, so
a JSON file would force everyone to run a local server. A <script> tag loads fine
from disk, which is why the studio opens by double-clicking index.html.

Source: Natural Earth 1:50m "land" (public domain, naturalearthdata.com).
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(ROOT, "series", "data", "ne_50m_land.geojson")
OUT = os.path.join(HERE, "data", "land.js")

# Generous: wider than any single session's map so you can always pan out.
BBOX = (-22.0, -2.0, 100.0, 60.0)   # lon0, lat0, lon1, lat1
PRECISION = 3                        # ~110 m at the equator
MIN_AREA = 0.0008                    # deg^2; drops specks, keeps Malta and Bahrain


def clip_edge(pts, inside, intersect):
    """One pass of Sutherland-Hodgman against a single half-plane."""
    if not pts:
        return []
    out = []
    prev = pts[-1]
    prev_in = inside(prev)
    for cur in pts:
        cur_in = inside(cur)
        if cur_in:
            if not prev_in:
                out.append(intersect(prev, cur))
            out.append(cur)
        elif prev_in:
            out.append(intersect(prev, cur))
        prev, prev_in = cur, cur_in
    return out


def clip_ring(ring, bbox):
    x0, y0, x1, y1 = bbox

    def ix(a, b, x):
        t = (x - a[0]) / (b[0] - a[0])
        return [x, a[1] + t * (b[1] - a[1])]

    def iy(a, b, y):
        t = (y - a[1]) / (b[1] - a[1])
        return [a[0] + t * (b[0] - a[0]), y]

    pts = [list(p[:2]) for p in ring]
    pts = clip_edge(pts, lambda p: p[0] >= x0, lambda a, b: ix(a, b, x0))
    pts = clip_edge(pts, lambda p: p[0] <= x1, lambda a, b: ix(a, b, x1))
    pts = clip_edge(pts, lambda p: p[1] >= y0, lambda a, b: iy(a, b, y0))
    pts = clip_edge(pts, lambda p: p[1] <= y1, lambda a, b: iy(a, b, y1))
    return pts


def area(pts):
    a = 0.0
    n = len(pts)
    for i in range(n):
        x0, y0 = pts[i]
        x1, y1 = pts[(i + 1) % n]
        a += x0 * y1 - x1 * y0
    return abs(a) / 2.0


def tidy(pts):
    """Round, then drop points that repeat after rounding."""
    out = []
    for x, y in pts:
        p = (round(x, PRECISION), round(y, PRECISION))
        if not out or p != out[-1]:
            out.append(p)
    if len(out) > 1 and out[0] == out[-1]:
        out.pop()
    return out


def rings_of(geom):
    t = geom.get("type")
    if t == "Polygon":
        return list(geom["coordinates"])
    if t == "MultiPolygon":
        return [r for poly in geom["coordinates"] for r in poly]
    return []


def main():
    if not os.path.exists(SRC):
        sys.exit("missing source: %s" % SRC)
    with open(SRC, "r", encoding="utf-8") as fh:
        gj = json.load(fh)

    kept = []
    for feat in gj.get("features", []):
        for ring in rings_of(feat.get("geometry") or {}):
            clipped = clip_ring(ring, BBOX)
            if len(clipped) < 4:
                continue
            pts = tidy(clipped)
            if len(pts) < 4 or area(pts) < MIN_AREA:
                continue
            kept.append(pts)

    kept.sort(key=area, reverse=True)
    flat = [[c for p in ring for c in p] for ring in kept]
    payload = {"bbox": list(BBOX), "source": "Natural Earth 1:50m land (public domain)", "rings": flat}

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// generated by tools/mapstudio/build_land.py - do not hand-edit\n")
        fh.write("window.MS_LAND = ")
        json.dump(payload, fh, separators=(",", ":"))
        fh.write(";\n")

    pts = sum(len(r) for r in kept)
    print("rings %d  points %d  ->  %s  (%.0f KB)" % (len(kept), pts, OUT, os.path.getsize(OUT) / 1024.0))


if __name__ == "__main__":
    main()
